- block:
    - name: 拷贝 eventrouter 配置
      template: src=eventrouter/eventrouter.yaml.j2 dest={{ cluster_dir }}/yml/eventrouter.yaml

    - name: 创建 eventrouter 应用
      shell: "{{ base_dir }}/bin/kubectl apply -f {{ cluster_dir }}/yml/eventrouter.yaml"

  when: 'eventrouter_install == "yes"'
